# Generated by Django 3.1.5 on 2021-06-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='choice1_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='choice2_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
