# Generated by Django 3.1.5 on 2021-06-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210625_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='percentage1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='percentage2',
            field=models.IntegerField(default=0),
        ),
    ]
