# Generated by Django 3.1.5 on 2021-06-26 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_auto_20210625_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('choice', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
