# Generated by Django 3.1.5 on 2021-06-27 04:13

from django.db import migrations
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_poll_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voters',
            field=polls.models.ListField(default=''),
        ),
    ]
