# Generated by Django 3.1.5 on 2021-06-27 04:16

from django.db import migrations
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210627_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voters',
            field=polls.models.ListField(blank=True),
        ),
    ]
