# Generated by Django 3.1.5 on 2021-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210627_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voters',
            field=models.TextField(blank=True),
        ),
    ]
